services:
  postgres:
    image: postgres:16
    container_name: bistro-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bistrodb

  webapp:
    build: .
    container_name: bistro-webapp
    restart: always
    depends_on:
        postgres:
                condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RUNNING_IN_DOCKER: "true"

      
      # fix wrong internal port in docker
      Api__BaseUrl: "http://webapp:8080"

      # Correct DB connection string for Docker
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"

      # Auth0 settings
      Auth__Authority: "${AUTH_AUTHORITY}"
      Auth__ClientId: "${AUTH_CLIENTID}"
      Auth__ClientSecret: "${AUTH_CLIENTSECRET}"

    ports:
      - "7015:8080"

    volumes:
      # Persist ASP.NET DataProtection Keys (fixes antiforgery + auth cookie issues)
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys

volumes:
  postgres-data:
  dataprotection-keys:
